platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do

    pod 'Hyphenate', '~> 3.3.2'
    
	pod 'EaseUI', :path => '../EaseUI'

	pod 'RedpacketAliAuthLib','~> 2.0.1'
	
	#pod 'Hyphenate_VideoRecoder', :path => '../HyphenateVideoRecoder'

end

target 'ChatDemo-UI3.0-JDPay' do
    
    pod 'Hyphenate', '~> 3.3.2'
    
	pod 'EaseUI', :path => '../EaseUI'
    
    	pod 'RedpacketLib'

end
