platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-aplipayOpenUI' do

    pod 'Hyphenate', '~> 3.3.2'
    
	pod 'EaseUI', :path => '../EaseUI'
    
    pod 'RedPacketAliAuthUI', :path => '../cocoapods-redpacket-ui-2.0.0'
	
	#pod 'Hyphenate_VideoRecoder', :path => '../HyphenateVideoRecoder'

end

target 'ChatDemo-JDpay' do
    
    pod 'Hyphenate', '~> 3.3.2'
    
    pod 'EaseUI', :path => '../EaseUI'
    
    pod 'RedpacketLib'
    
    #pod 'Hyphenate_VideoRecoder', :path => '../HyphenateVideoRecoder'
    
end



